"""The edits made to the generated plan at approval, as a script so they are reproducible.

    python3 plans/approve_ja.py    # reads plans/generated-raw.json, writes plans/interview-ja.json
"""
import json, pathlib

HERE = pathlib.Path(__file__).parent
raw = json.loads((HERE / "generated-raw.json").read_text())

NOTE = (
    "Generated by `--plan brief.md` with z-ai/glm-5.3-flash (second attempt; the first wrote "
    "done_threshold 1, out of bounds), then approved with these edits, applied by plans/approve_ja.py. "
    "(1) Every rubric came back best-first; the program reads level 0 as the worst, so each "
    "question's rubric and the fit rubric were reversed. The fit rubric was also reordered so that "
    "'cannot be assessed' sits above 'irreconcilable conflict'. "
    "(2) per_dimension 1 -> 2, min_q 5 -> 8, max_q 8 -> 12, reserve_early 1 (unchanged): as written, "
    "coverage was met by the fourth answer and the budget ran to eight, so the judge chose almost "
    "nothing and `done` could not vary. Now 4 dimensions owe 8 answers, the budget is 12, and the "
    "pool is 16. (3) done_threshold 0.95 -> 0.5: the model's two attempts wrote 1 and then the "
    "bound's maximum, neither a considered number; 0.5 is the same provisional value the earlier "
    "50-interview plan ran under. (4) Six questions added by the approver, written in the same "
    "style, so the pool exceeds the budget and some questions go unasked: two per technical "
    "dimension. A second generated draft failed validation twice and was not used. "
    "(5) ui text -> textarea, with text also allowed: these questions want prose. "
    "(6) One typo fixed in rust_readiness (聞かせます -> 聞かせてください). "
    "(7) done.true: 'at least once' -> 'at least twice', to match per_dimension. "
    "Nothing else was changed; dimension names and weights are the model's.")

plan = dict(raw)
plan["policy"] = {**raw["policy"], "per_dimension": 2, "reserve_early": 1, "min_q": 8,
                  "max_q": 12, "done_threshold": 0.5}
plan["done"] = {"true": raw["done"]["true"].replace("最低1回ずつ", "最低2回ずつ"),
                "false": raw["done"]["false"]}
fit = raw["fit"]["rubric"]           # generated order: aligned, conditional, conflict, cannot assess
plan["fit"] = {"rubric": [fit[2], fit[3], fit[1], fit[0]]}

def approve(q):
    q = dict(q)
    q["rubric"] = list(reversed(q["rubric"]))
    q["ui"], q["ui_options"] = "textarea", ["textarea", "text"]
    if q["id"] == "rust_readiness":
        q["text"] = q["text"].replace("考えも聞かせます。", "考えも聞かせてください。")
    return q

D_JAVA, D_RUST, D_MONEY = (raw["dimensions"][i]["name"] for i in (0, 1, 2))

ADDED = [
    {"id": "java_recovery", "dimension": D_JAVA,
     "text": "本番のJavaサービスで、障害やバグの後にデータの整合性を回復した経験を教えてください。何が壊れていて、どう範囲を特定し、どう直し、直したことをどう確認しましたか。",
     "context": "java_tx_designやjava_opsで設計・運用の話は出たが、壊れたデータを自分の手で直した経験がまだ見えていない場合。障害対応の話の後で聞くと自然。",
     "options": None,
     "rubric": [
         "本番データの整合性を回復した経験そのものが語れない。個人学習の範囲の話、または質問と関係のない経歴の説明に流れる。",
         "整合性の回復はDBAや別チームが担ったため、自分は関わっていないと説明する。範囲の特定や確認の手順を聞き返しても、見ていたもの、取った対応を具体的に語れない。",
         "回復の手順（範囲の特定、修正、確認）を正しく一般論として説明でき、用語も正確だが、自分のサービスでの実例（何件、どの期間、どう確認したか）が出てこない。流暢だが本人の経験としての数字や失敗がない。",
         "自分が担当した本番サービスでの具体的な不整合（例：二重計上、欠落した仕訳、途中で止まったバッチ）を挙げ、影響範囲をどう特定したか（クエリ、件数、期間）、修正の方法（上書きではなく訂正の記録、バックフィル）、修正後の確認方法（突合、再計算）を数字を伴って語る。最初の見立てが外れた場合はそれも語れる。"],
     "ui": "textarea", "ui_options": ["textarea", "text"]},
    {"id": "java_perf_change", "dimension": D_JAVA,
     "text": "本番のJavaサービスで、計測に基づいてレイテンシやスループットを改善した経験を教えてください。改善前後の数字と、試したが効かなかった対策があればそれも教えてください。",
     "context": "Javaの実務経験は語られたが、計測に基づく判断ができるかがまだ見えていない場合。運用の質問（java_ops）の代わり、または補足として聞く。",
     "options": None,
     "rubric": [
         "本番でのパフォーマンス改善の経験が語れない。個人開発の範囲、または質問と関係のない話に流れる。",
         "改善はチームや他のメンバーが行い、自分は計測にも変更にも直接関わっていない。何を見て判断したかを聞き返しても具体的に語れない。",
         "「プロファイルして、キャッシュを入れて速くなった」といった一般的な流れは語れるが、改善前後の数字、計測に使った手段、効かなかった対策が出てこない。手法の名前は多いが、判断の根拠が本人の経験として語られない。",
         "自分が計測した本番の数値（p99、スループット、GC停止時間など）を改善前後で挙げ、何を根拠にどの変更を選んだか、効かなかった対策とそこから何を学んだかまで語る。改善の副作用や、戻せるように出した工夫についても触れる。"],
     "ui": "textarea", "ui_options": ["textarea", "text"]},
    {"id": "rust_hands_on", "dimension": D_RUST,
     "text": "実際に書いたRustのコード（実務でも個人プロジェクトでも構いません）で、所有権、ライフタイム、非同期のいずれかで詰まった箇所と、どう解決したかを教えてください。まだ書いたことがなければ、そう言ってください。",
     "context": "rust_readinessでRustの経験や学習について語られた後、それが実際のコードに裏付けられているかを確認したい場合。実務経験があると言った直後に聞くと有効。",
     "options": None,
     "rubric": [
         "Rustのコードを書いたことがなく、それを認めるか、または質問をJavaの話や関係のない経歴の話にすり替える。",
         "書いたことはあると言うが、詰まった箇所も解決の過程も語れない。「チュートリアルを写した」程度の経験にとどまり、所有権やライフタイムについて自分が理解した点を説明できない。",
         "所有権、借用チェッカー、ライフタイム、async/awaitについて正確に説明できるが、自分のコードでどこが通らず、どう直したかの実例が出てこない。入門書の説明の再現で、本人の手が動いた痕跡がない。",
         "自分のコードで具体的に何がコンパイルを通らなかったか（例：借用の競合、ライフタイムの注釈、Send/Syncの制約、tokioのランタイム境界）を挙げ、どう直したか、その解決をどう理解したかを自分の言葉で語る。実務であれば本番のどの部分か、個人であれば何を作ったかが具体的に出てくる。"],
     "ui": "textarea", "ui_options": ["textarea", "text"]},
    {"id": "rust_when_not", "dimension": D_RUST,
     "text": "当社は全面的な書き換えをしません。Rustに移すべきでない部分とはどんなものだと考えますか。過去に、書き換えたい気持ちを抑えてJavaや既存の言語のままにした経験があれば、それも教えてください。",
     "context": "rust_boundaryの代わり、またはその後に聞く。応募者がRustへの熱意を強く語った場合に、境界を決めてから書き直すという当社の進め方に合うかを確認する質問。",
     "options": None,
     "rubric": [
         "質問に答えられない、または「すべてRustにすべき」といった全面書き換えを技術的な好みとして主張し、計測や合意の話が出てこない。",
         "移すべきでない部分について一般論（「安定しているものは触らない」）は語れるが、判断基準が語れず、自分の経験としての実例もない。",
         "判断基準（変更頻度、レイテンシ要件、チームの習熟、境界の切りやすさ、移行の検証方法）を正しく説明できるが、自分がその判断をした実例がなく、教科書的な説明にとどまる。",
         "移さない判断の基準を自分の言葉で語り、実際に書き換えの誘惑を抑えた経験（何を、なぜ、どう計測して、チームとどう合意したか）を具体的に挙げる。移行の対象と対象外を分けた根拠が計測と合意に基づいている。"],
     "ui": "textarea", "ui_options": ["textarea", "text"]},
    {"id": "reconciliation_mismatch", "dimension": D_MONEY,
     "text": "精算や突合で数字が合わなかった具体的な出来事を教えてください。何がどれだけずれていて、どう気づき、原因は何で、どう正しましたか。確定後のデータをどう扱ったかも含めてお願いします。",
     "context": "money_correctnessで冪等性の話は出たが、実際に数字のずれを追った経験がまだ見えていない場合。お金を扱うシステムの経験があると言った応募者には早めに聞いてよい。",
     "options": None,
     "rubric": [
         "数字のずれを追った経験が語れない。突合の概念の説明も曖昧、または質問と関係のない経歴の話に流れる。",
         "ずれがあったことは語るが、調査は他の人が行い、自分の役割を聞き返しても具体的に説明できない。原因や修正の方法が「対応しました」で終わる。",
         "突合のずれの典型的な原因（タイムゾーン境界、丸め、遅延到着の返金、二重イベント）と修正の原則（上書きせず訂正仕訳）を正確に説明できるが、自分が追った実例、その数字、かかった時間が出てこない。",
         "自分が追った具体的なずれ（金額、件数、いつ気づいたか）を挙げ、原因の切り分け方、原因、修正の方法（確定後は上書きせず新しい記録で正した、など）、再発防止までを数字と期間を伴って語る。見立てが外れた過程も語れる。"],
     "ui": "textarea", "ui_options": ["textarea", "text"]},
    {"id": "prod_data_verification", "dimension": D_MONEY,
     "text": "本番のデータや残高を使って動作を確かめたくなった場面はありますか。そのとき実際にどうしましたか。検証環境で再現できないとき、あなたはどう確認しますか。",
     "context": "お金の正しさの質問の後、または応募者が本番環境での確認や実験に触れた直後。行動原則「お金は試験環境ではない」との一致を見る質問。",
     "options": None,
     "rubric": [
         "本番のデータや残高で検証したことを問題視しない、または検証できない変更をそのまま出したことを肯定的に語る。",
         "本番で確認したい場面の経験がなく、検証環境で再現できないときにどうするかについても「慎重にやります」以上の具体的な方法が語れない。",
         "本番データを使わない原則と代替手段（マスキングした複製、シャドウ実行、読み取り専用の照合、段階的リリース）を正しく説明できるが、自分がその判断をした実例が出てこない。",
         "本番で確かめたくなった具体的な場面を挙げ、実際に取った方法（マスキングした複製での再現、シャドウ実行での比較、読み取り専用の突合、カナリア）と、その判断の根拠、かかったコストを語る。本番で確認せざるを得なかった場合は、宣言、記録、影響の限定をどう行ったかまで語れる。"],
     "ui": "textarea", "ui_options": ["textarea", "text"]},
]

plan["questions"] = [approve(q) for q in raw["questions"]] + ADDED
plan["source"] = {**raw["source"], "note": NOTE}
(HERE / "interview-ja.json").write_text(json.dumps(plan, ensure_ascii=False, indent=1) + "\n",
                                        encoding="utf-8")
print(f"wrote interview-ja.json: {len(plan['questions'])} questions")
